POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token:{{token}}

{
  "name": "litao4",
  "idCard": "13576478347",
  "type": "1"
}

###
GET http://localhost:8000/member/passenger/query-list?page=2&size=2
Content-Type: application/json
token:{{token}}

