server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: qwe`123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: true
      time-to-live: 60s

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    local-cache-scope: statement #配置为statemenet，及关闭一级缓存，配置为session级别就是开启

logging:
  level:
    com.litao.train.business.mapper: trace

rocketmq:
  name-server: http://43.137.12.232:9876
  producer:
    group: litao